create_countries = '''CREATE TABLE IF NOT EXISTS COUNTRIES(
    ID SERIAL PRIMARY KEY,
    ISO_CODE       TEXT    NOT NULL,
    NAME           TEXT    NOT NULL,
    SOURCE_NAME    TEXT,
    SOURCE_WEBSITE TEXT,
    UNIQUE(ISO_CODE)
    );
    
    CREATE INDEX IF NOT EXISTS idx_countries_code ON COUNTRIES(ISO_CODE);'''

create_registers = '''CREATE TABLE IF NOT EXISTS VACC_REGISTERS(
    ID SERIAL PRIMARY KEY,
    COUNTRY_ID                      INT NOT NULL REFERENCES COUNTRIES(ID),
    DATE_REPORTED                   DATE    NOT NULL,
    TOTAL_VACCINATIONS              INT,
    PEOPLE_VACCINATED               INT,
    PEOPLE_FULLY_VACCINATED         INT,
    DAILY_VACCINATIONS_RAW          INT,
    DAILY_VACCINATIONS              INT,
    TOTAL_VACCINATIONS_PER_HUNDRED  FLOAT,
    PEOPLE_VACCINATED_PER_HUNDRED   FLOAT,
    PEOPLE_FULLY_VACCINATED_PER_HUNDRED FLOAT,
    DAILY_VACCINATIONS_PER_MILLION  FLOAT
    );
    
    CREATE INDEX IF NOT EXISTS idx_vacc_registers_date ON VACC_REGISTERS(DATE_REPORTED);'''